---
routers:
    - opdx-a3-r1-oob.ops.puppetlabs.net
    - pix-jj09c-r1-oob.ops.puppetlabs.net
srx:
    - opdx-a3-fw1.ops.puppetlabs.net
    - opdx-fw3.ops.puppetlabs.net
    - pdx-626c2-fw1.ops.puppetlabs.net
    - lhr-cab-fw1.ops.puppetlabs.net
switches:
    - opdx-a3-core.ops.puppetlabs.net
    - opdx-edge-vc1.ops.puppetlabs.net
    - opdx-storage-vc1.ops.puppetlabs.net
    - pdx-528r1-vc1-oob.ops.puppetlabs.net
    - pdx-626c1-vc1-oob.ops.puppetlabs.net
    - pdx-626c2-core.ops.puppetlabs.net
    - pdx-626c3-s1-oob.ops.puppetlabs.net
    - pdx-626c4-s1-oob.ops.puppetlabs.net
    - pdx-oob.ops.puppetlabs.net
    - pdx-wifi-vc1-oob.ops.puppetlabs.net
    - lhr-cab-core.ops.puppetlabs.net
